-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 03 Des 2019 pada 06.57
-- Versi server: 10.1.36-MariaDB
-- Versi PHP: 5.6.38

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `toko_laptop`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `tabel_hp`
--

CREATE TABLE `tabel_hp` (
  `id_barang` int(11) NOT NULL,
  `merk_barang` varchar(120) NOT NULL,
  `harga` varchar(200) NOT NULL,
  `keterangan` text NOT NULL,
  `stok` int(10) NOT NULL,
  `gambar` text NOT NULL,
  `gambar_2` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tabel_hp`
--

INSERT INTO `tabel_hp` (`id_barang`, `merk_barang`, `harga`, `keterangan`, `stok`, `gambar`, `gambar_2`) VALUES
(1, 'HP Core i5 14s-CF2005TX(Gold)', 'Rp8.249.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: Intel® Core™ i5-10210U (1.6 GHz base frequency, up to 4.2 GHz base with Intel® Turbo Boost Technology, 6 MB cache, 4 cores)\r\nProcessor family: 10th Generation Intel® Core™ i5 processor\r\nChipset: Intel® Integrated SoC\r\nForm factor: Standard laptop\r\nMemory: 4 GB DDR4-2666 SDRAM (1 x 4 GB)\r\nMemory Note: Transfer rates up to 2666 MT/s.\r\nInternal storage: 1 TB 5400 rpm SATA\r\nStorage type: HDD\r\nDisplay: 14\" diagonal HD SVA BrightView micro-edge WLED-backlit (1366 x 768)\r\nGraphics: AMD Radeon™ 530 Graphics (2 GB GDDR5 dedicated)\r\nPorts: 1 HDMI 1.4; 1 headphone/microphone combo; 1 RJ-45; 1 AC smart pin; 2 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 USB 3.1 Gen 1 Type-C™ (Data Transfer Only, 5 Gb/s signaling rate)\r\nExpansion slots: 1 multi-format SD media card reader\r\nAudio features: Dual speakers\r\nWebcam: HP TrueVision HD Camera with integrated digital microphone\r\nPointing device: Touchpad with multi-touch gesture support; Precision Touchpad Support\r\nKeyboard: Full-size island-style ash silver backlit keyboard\r\nNetwork interface: Integrated 10/100/1000 GbE LAN\r\nWireless: Realtek 802.11 a/b/g/n/ac (1x1) Wi-Fi® and Bluetooth® 4.2 Combo\r\nWireless note: Miracast compatible\r\nPower supply type: 65 W AC power adapter\r\nBattery type: 3-cell, 41 Wh Li-ion\r\nBattery weight: 210 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 32.4 x 22.59 x 1.99 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nBerat: Starting at 1.43 kg\r\nWeight note (metric): Weight varies by configuration\r\nProduct color: Gold\r\nSecurity management: Kensington Mini Security slot™\r\nHP apps: HP Audio Switch; HP Documentation; HP ePrint; HP e-Service; HP JumpStart; HP Recovery Manager; HP Support Assistant; HP Connection Optimizer\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: Netflix (30-day free trial offer)\r\nSoftware - Productivity & finance: 1 month trial for new Microsoft Office 365 customers\r\nJaminan: 1 year limited parts and labour', 10, '14s-CF2005TX(Gold).jpg', '14s-CF2005TX(Gold) 2.jpg'),
(2, 'HP Pavilion Core i7 14-CE2013TX(White)', 'RP13.699.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: Intel® Core™ i7-8565U (1.8 GHz base frequency, up to 4.6 GHz with Intel® Turbo Boost Technology, 8 MB cache, 4 cores)\r\nProcessor family: 8th Generation Intel® Core™ i7 processor\r\nChipset: Intel® Integrated SoC\r\nForm factor: Standard laptop\r\nMemory: 8 GB DDR4-2400 SDRAM (1 x 8 GB)\r\nMemory Note: Transfer rates up to 2400 MT/s.\r\nInternal storage: 1 TB 5400 rpm SATA\r\nHard drive (2nd): 256 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: SSD; HDD\r\nCloud service: Dropbox\r\nDisplay: 14\" diagonal FHD IPS anti-glare micro-edge WLED-backlit (1920 x 1080)\r\nGraphics: NVIDIA® GeForce® MX250 (2 GB GDDR5 dedicated)\r\nPorts: 1 USB 3.1 Gen 1 Type-C™ (Data Transfer Only, 5 Gb/s signaling rate); 2 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 RJ-45; 1 AC smart pin; 1 HDMI; 1 headphone/microphone combo\r\nExpansion slots: 1 multi-format SD media card reader\r\nAudio features: B&O, dual speakers, HP Audio Boost\r\nWebcam: HP Wide Vision HD Camera with integrated dual array digital microphone\r\nSensors: Accelerometer\r\nPointing device: HP Imagepad with multi-touch gesture support\r\nKeyboard: Full-size island-style natural silver backlit keyboard\r\nNetwork interface: Integrated 10/100/1000 GbE LAN\r\nWireless: Intel® Wireless-AC 9560 802.11a/b/g/n/ac (2x2) Wi-Fi® and Bluetooth® 5 Combo\r\nWireless note: MU-MIMO supported; Miracast compatible\r\nPower supply type: 65 W AC power adapter\r\nBattery type: 3-cell, 41 Wh Li-ion\r\nBattery weight: 210 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 32.68 x 22.55 x 1.79 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nBerat: Starting at 1.6 kg\r\nPackage weight: 2.99 kg\r\nProduct color: White & Gold\r\nSecurity management: Kensington Nano Security Slot™; Fingerprint reader\r\nHP apps: HP Audio Switch; HP CoolSense; HP Documentation; HP ePrint; HP JumpStart; HP Support Assistant; HP Connection Optimizer; HP Privacy Settings; HP BIOS Recovery\r\nSoftware included: McAfee LiveSafe™\r\nJaminan: 1 year limited parts and labour\r\n', 10, '14-CE2013TX(White).png', '14-CE2013TX(White) 2.png'),
(3, 'HP Pavilion x360 Core i7 14-DH1006TX(Gold)', 'RP14.699.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: Intel® Core™ i7-10510U (1.8 GHz base frequency, up to 4.9 GHz base with Intel® Turbo Boost Technology, 8 MB cache, 4 cores)\r\nProcessor family: 10th Generation Intel® Core™ i7 processor\r\nChipset: Intel® Integrated SoC\r\nForm factor: Convertible\r\nMemory: 8 GB DDR4-2666 SDRAM (1 x 8 GB)\r\nMemory Note: Transfer rates up to 2666 MT/s.\r\nInternal storage: 512 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: SSD\r\nCloud service: Dropbox\r\nDisplay: 14\" diagonal FHD IPS anti-glare micro-edge WLED-backlit touch screen (1920 x 1080)\r\nGraphics: NVIDIA® GeForce® MX250 (2 GB GDDR5 dedicated)\r\nPorts: 1 USB 3.1 Gen 1 Type-C™ (Data Transfer Only, 5 Gb/s signaling rate); 2 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 AC smart pin; 1 HDMI 1.4; 1 headphone/microphone combo\r\nExpansion slots: 1 multi-format SD media card reader\r\nAudio features: B&O, dual speakers, HP Audio Boost\r\nWebcam: HP Wide Vision HD Camera with integrated dual array digital microphone\r\nSensors: Accelerometer; Gyroscope; eCompass\r\nPointing device: HP Imagepad with multi-touch gesture support; Precision Touchpad Support\r\nKeyboard: Full-size island-style luminous gold backlit keyboard\r\nWireless: 802.11ac (1x1) Wi-Fi® and Bluetooth® 4.2 combo\r\nWireless note: MU-MIMO supported; Miracast compatible\r\nPower supply type: 65 W Smart AC power adapter\r\nBattery type: 3-cell, 41 Wh Li-ion\r\nBattery weight: 210 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 32.4 x 22.29 x 1.97 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nBerat: Starting at 1.58 kg\r\nWeight note (metric): Weight varies by configuration\r\nProduct color: Warm Gold & Silver\r\nSecurity management: Kensington Nano Security Slot™; Fingerprint reader\r\nHP apps: HP 3D DriveGuard; HP Audio Switch; HP JumpStart; HP CoolSense; HP Documentation; HP Support Assistant; HP Connection Optimizer; HP Privacy Settings\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: B&O Audio; Amazon Alexa on Windows\r\nJaminan: 1 year limited parts and labour\r\n', 10, '14-DH1006TX(Gold) 1.png', '14-DH1006TX(Gold) 2.png'),
(4, '13-AP0056TU(Black-Gold) HP Spectre x360 Core i7', 'Rp25.499.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: Intel® Core™ i7 8565U (1.8 GHz base frequency(2b), up to 4.6 GHz with Intel® Turbo Boost Technology(2g), 8 MB cache, 4 cores)\r\nProcessor family: 8th Generation Intel® Core™ i7 processor\r\nForm factor: Convertible\r\nMemory: 16 GB DDR4-2400 SDRAM (onboard)\r\nMemory Note: Transfer rates up to 2400 MT/s.\r\nInternal storage: 512 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: SSD\r\nCloud service: Dropbox\r\nDisplay: HP Sure View Integrated Privacy Screen 13.3\" diagonal FHD IPS anti-glare micro-edge WLED-backlit touch screen (1920 x 1080)\r\nGraphics: Intel® UHD Graphics 620\r\nPorts: 2x USB Type-C™ 3.1 Gen 2 (Thunderbolt™ 3, DP 1.2, PD 3.0, Data transfer, HP Sleep and Charge ); 1x USB 3.1 Gen2 Type-A™ (HP Sleep and Charge); 1 headphone/microphone combo\r\nExpansion slots: 1 microSD media card reader\r\nAudio features: Bang & Olufsen; quad speakers; HP Audio Boost 2.0\r\nWebcam: HP Wide Vision FHD IR Camera with integrated dual array digital microphone\r\nSensors: Accelerometer; Gyroscope; eCompass\r\nPointing device: HP SecurePad with multi-touch gesture support\r\nKeyboard: Full-size island-style backlit keyboard\r\nWireless: Intel® Wireless-AC 9560 802.11a/b/g/n/ac (2x2) Wi-Fi® and Bluetooth® 5 Combo\r\nWireless note: MU-MIMO supported; Miracast compatible\r\nPower supply type: 65 W USB Type-C™ adapter\r\nBattery type: 4-cell, 61 Wh Li-ion\r\nBattery weight: 250 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 30.88 x 21.79 x 1.45 cm\r\nBerat: Starting at 1.32 kg\r\nProduct color: Black-Gold & Blue\r\nSecurity management: Trusted Platform Module (TPM) support; Privacy Camera Kill Switch\r\nHP apps: HP Audio Switch; HP Documentation; HP ePrint; HP e-Service; HP JumpStart; HP Support Assistant; HP Connection Optimizer; HP Command Center; HP PC Hardware Diagnostics Windows\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: iQiyi\r\nJaminan: 2 year limited parts and labour\r\n', 10, '13-AP0056TU(Black Gold) 1.png', '13-AP0056TU(Black Gold) 2.png'),
(5, 'HP Envy AMD x360 13-AR0009AU(Black)', 'RP17.499.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: AMD Ryzen™ 7 3700U with Radeon™ Vega 10 Graphics (2.3 GHz base clock, up to 4 GHz max boost clock, 6 MB cache, 4 cores)\r\nProcessor family: AMD Ryzen™ 7 processor\r\nChipset: AMD Integrated SoC\r\nForm factor: Convertible\r\nSpecial features: Convertible\r\nMemory: 16 GB DDR4-2400 SDRAM (onboard)\r\nMemory Note: Transfer rates up to 2400 MT/s.\r\nInternal storage: 512 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: SSD\r\nOptical drive: Optical drive not included\r\nCloud service: Dropbox\r\nDisplay: 13.3\" diagonal FHD IPS micro-edge WLED-backlit touch screen with Corning® Gorilla® Glass NBT™ (1920 x 1080)\r\nGraphics: AMD Radeon™ RX Vega 10 Graphics\r\nPorts: 1 USB 3.1 Gen 1 Type-C™ (5 Gb/s signaling rate, Power Delivery 3.0, DisplayPort™ 1.4, HP Sleep and Charge); 1 USB 3.1 Gen 1 Type-A (HP Sleep and Charge); 1 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 headphone/microphone combo\r\nExpansion slots: 1 multi-format SD media card reader\r\nAudio features: Bang & Olufsen, quad speakers, HP Audio Boost\r\nWebcam: HP Wide Vision HD Camera with integrated dual array digital microphone\r\nSensors: Accelerometer; Gyroscope; Magentometer\r\nPointing device: HP Imagepad with multi-touch gesture support; Precision Touchpad Support\r\nKeyboard: Full-size island-style nightfall black backlit keyboard\r\nWireless: 802.11ac (2x2) Wi-Fi® and Bluetooth® 4.2 combo\r\nWireless note: Miracast compatible\r\nPower supply type: 65 W AC power adapter\r\nBattery type: 4-cell, 53 Wh Li-ion polymer\r\nBattery weight: 210 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 30.6 x 21.2 x 1.47 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nBerat: Starting at 1.31 kg\r\nProduct color: Nightfall black\r\nSecurity management: Privacy camera kill switch\r\nHP apps: HP Audio Switch; HP Documentation; HP e-Service; HP JumpStart; HP Support Assistant; HP Connection Optimizer; HP Command Center; HP PC Hardware Diagnostics Windows\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: iQiyi\r\nJaminan: 1 year limited parts and labour\r\n', 10, '13-AR0009AU(Black) 1.png', '13-AR0009AU(Black) 2.png'),
(6, 'HP Envy Core i7 13-AQ0018TX(Gold)', 'Rp19.999.000', 'Prosesor: Intel® Core™ i7 8565U (1.8 GHz base frequency, up to 4.6 GHz with Intel® Turbo Boost Technology, 8 MB cache, 4 cores)\r\nProcessor family: 8th Generation Intel® Core™ i7 processor\r\nChipset: Intel® Integrated SoC\r\nForm factor: Standard laptop\r\nMemory: 16 GB DDR4-2400 SDRAM (onboard)\r\nMemory Note: Transfer rates up to 2400 MT/s.\r\nInternal storage: 512 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: SSD\r\nCloud service: Dropbox\r\nDisplay: 13.3\" diagonal FHD IPS BrightView micro-edge WLED-backlit touch screen (1920 x 1080)\r\nGraphics: NVIDIA® GeForce® MX250 (2 GB GDDR5 dedicated)\r\nPorts: 1 USB 3.1 Gen 1 Type-C™ (5 Gb/s signaling rate, Power Delivery 3.0, DisplayPort™ 1.2, HP Sleep and Charge); 1 USB 3.1 Gen 1 Type-A (HP Sleep and Charge); 1 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 AC smart pin; 1 headphone/microphone combo\r\nExpansion slots: 1 microSD media card reader\r\nAudio features: B&O, quad speakers, HP Audio Boost, HP Far-field Cortana support\r\nWebcam: HP Wide Vision HD Camera with integrated dual array digital microphone\r\nPointing device: HP Imagepad with multi-touch gesture support; Precision Touchpad Support\r\nKeyboard: Full-size island-style pale gold backlit keyboard\r\nWireless: Intel® Wireless-AC 9560 802.11a/b/g/n/ac (2x2) Wi-Fi® and Bluetooth® 5 Combo\r\nWireless note: MU-MIMO supported; Miracast compatible\r\nPower supply type: 65 W AC power adapter\r\nBattery type: 4-cell, 53 Wh Li-ion polymer\r\nBattery weight: 210 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified; EPEAT® Silver registered\r\nDimensions without stand (W x D x H): 30.7 x 21.15 x 1.47 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nPackage dimensions (W x D x H): 52 x 30.5 x 6.9 cm\r\nBerat: Starting at 1.17 kg\r\nProduct color: Gold & Silver\r\nSecurity management: Privacy camera kill switch\r\nHP apps: HP Audio Switch; HP Documentation; HP e-Service; HP JumpStart; HP Support Assistant; HP Connection Optimizer; HP Command Center; HP PC Hardware Diagnostics Windows\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: iQiyi\r\nJaminan: 1 year limited parts and labour\r\n', 10, '13-AQ0018TX(Gold) 1.png', '13-AQ0018TX(Gold) 2.png'),
(7, 'HP Gaming OMEN 15-DH0105TX Black', 'RP23.999.000', 'Operating system: Windows 10 Home Single Language 64\r\nProsesor: Intel® Core™ i7-9750H (2.6 GHz base frequency, up to 4.5 GHz base with Intel® Turbo Boost Technology, 12 MB cache, 6 cores)\r\nProcessor family: 9th Generation Intel® Core™ i7 processor\r\nChipset: Intel® HM370\r\nForm factor: Standard laptop\r\nMemory: 16 GB DDR4-2666 SDRAM (2 x 8 GB)\r\nMemory Note: Transfer rates up to 2666 MT/s.\r\nInternal storage: 1 TB 7200 rpm SATA\r\nHard drive (2nd): 512 GB PCIe® NVMe™ M.2 SSD\r\nStorage type: HDD; SSD\r\nCloud service: Dropbox\r\nDisplay: 15.6\" diagonal FHD 144 Hz IPS anti-glare micro-edge WLED-backlit (1920 x 1080) 144hz refresh rate\r\nGraphics: NVIDIA® GeForce® RTX 2060 Graphics (6 GB GDDR6 dedicated)\r\nPorts: 1 USB 3.1 Gen 2 Type-C™ with Thunderbolt™ 3 (40 Gb/s signaling rate, DisplayPort™ 1.4, HP Sleep and Charge); 3 USB 3.1 Gen 1 Type-A; 1 HDMI; 1 RJ-45; 1 headphone/microphone combo; 1 microphone; 1 AC smart pin; 1 Mini DisplayPort™\r\nExpansion slots: 1 multi-format SD media card reader\r\nAudio features: Bang & Olufsen; dual speakers; HP Audio Boost; Omen Audio Control Support DTS:X® Ultra\r\nWebcam: HP Wide Vision HD Camera with integrated dual array digital microphone\r\nSensors: Accelerometer\r\nPointing device: Touchpad with multi-touch gesture support and 26-Key Rollover Anti-Ghosting Key technology\r\nKeyboard: Full-size island-style white legend 4-zone lighting RGB backlit keyboard with numeric keypad\r\nNetwork interface: Integrated 10/100/1000 GbE LAN\r\nWireless: Intel® Wireless-AC 9560 (2x2) Wi-Fi® and Bluetooth® 5 Combo (Supporting gigabit file transfer speeds)\r\nWireless note: MU-MIMO supported; Miracast compatible\r\nPower supply type: 200 W AC power adapter\r\nBattery type: 6-cell, 69 Wh Li-ion polymer\r\nBattery weight: 290 g\r\nEnergy Efficiency Compliance: ENERGY STAR® certified\r\nDimensions without stand (W x D x H): 36 x 26 x 2 cm\r\nDimension note (metric): Dimensions vary by configuration\r\nPackage dimensions (W x D x H): 55.2 x 30.5 x 6.9 cm\r\nBerat: Starting at 2.4 kg\r\nPackage weight: 3.84 kg\r\nProduct color: Black\r\nHP apps: HP 3D DriveGuard; HP Audio Switch; HP Documentation; HP JumpStart; HP Support Assistant; HP Connection Optimizer; HP PC Hardware Diagnostics Windows; HP BIOS Recovery\r\nSoftware included: McAfee LiveSafe™\r\nPre-installed software: iQiyi\r\nJaminan: 2 year limited parts and labour', 10, 'OMEN 15-DH0105TX Black 1.png', 'OMEN 15-DH0105TX Black 2.png');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `tabel_hp`
--
ALTER TABLE `tabel_hp`
  ADD PRIMARY KEY (`id_barang`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `tabel_hp`
--
ALTER TABLE `tabel_hp`
  MODIFY `id_barang` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
